# Generated by Django 5.1.15 on 2026-09-29 02:47

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import events.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("location_name", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "invite_code",
                    models.CharField(
                        default=events.models.new_invite_code,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "is_standing",
                    models.BooleanField(
                        default=False,
                        help_text="Recurring host mode: a standing list not tied to a date.",
                    ),
                ),
                ("last_bulk_reminder_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="AICertificateRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_to_email", models.EmailField(max_length=254)),
                ("wording", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "upload_token",
                    models.CharField(default=events.models.new_token, max_length=64, unique=True),
                ),
                ("token_expires_at", models.DateTimeField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("min_gl_per_occurrence", models.PositiveIntegerField(default=1000000)),
                ("min_gl_aggregate", models.PositiveIntegerField(default=2000000)),
                ("require_auto", models.BooleanField(default=True)),
                ("require_liquor", models.BooleanField(default=False)),
                ("additional_insured_text", models.TextField(blank=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement",
                        to="events.event",
                    ),
                ),
                (
                    "required_document_types",
                    models.ManyToManyField(blank=True, to="documents.documenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("festival", "Festival"),
                            ("venue", "Venue"),
                            ("truck_park", "Truck park"),
                            ("brewery", "Brewery"),
                            ("office", "Office park"),
                            ("other", "Other"),
                        ],
                        default="festival",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        default="pilot",
                        help_text="Billing plan; unused until payments ship.",
                        max_length=40,
                    ),
                ),
                (
                    "recurring_host",
                    models.BooleanField(
                        default=False,
                        help_text="Keeps a standing vendor list evaluated against today's date.",
                    ),
                ),
                (
                    "owner_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.organization",
            ),
        ),
        migrations.CreateModel(
            name="RequirementTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("min_gl_per_occurrence", models.PositiveIntegerField(default=1000000)),
                ("min_gl_aggregate", models.PositiveIntegerField(default=2000000)),
                ("require_auto", models.BooleanField(default=True)),
                ("require_liquor", models.BooleanField(default=False)),
                (
                    "required_document_types",
                    models.ManyToManyField(blank=True, to="documents.documenttype"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventVendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("joined", "Joined"),
                            ("removed", "Removed"),
                        ],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "computed_status",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="red",
                        max_length=10,
                    ),
                ),
                (
                    "status_reasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_links",
                        to="events.event",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_links",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("event", "vendor"), name="unique_event_vendor")],
            },
        ),
    ]
