# Generated by Django 5.1.15 on 2026-09-29 02:47

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="COIDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("insurer_name", models.CharField(blank=True, max_length=200)),
                ("naic_number", models.CharField(blank=True, max_length=20)),
                ("policy_number", models.CharField(blank=True, max_length=80)),
                (
                    "gl_per_occurrence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("gl_aggregate", models.PositiveIntegerField(blank=True, null=True)),
                ("auto_liability", models.PositiveIntegerField(blank=True, null=True)),
                ("workers_comp", models.BooleanField(default=False)),
                (
                    "liquor_liability",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("additional_insureds", models.JSONField(blank=True, default=list)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=500)),
                ("thumbnail_path", models.CharField(blank=True, max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=60)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("vendor", "Vendor upload"),
                            ("agent", "Agent upload"),
                        ],
                        default="vendor",
                        max_length=10,
                    ),
                ),
                ("extracted", models.JSONField(blank=True, default=dict)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("extraction_model", models.CharField(blank=True, max_length=80)),
                (
                    "extraction_prompt_version",
                    models.CharField(blank=True, max_length=20),
                ),
                ("extraction_raw", models.TextField(blank=True)),
                (
                    "confirmed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields as confirmed by the vendor.",
                    ),
                ),
                (
                    "admin_confirmed",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields as confirmed by the admin.",
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "expiration_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("agent_email", "Agent email"),
                            ("agent_call", "Agent call"),
                            ("insurer_portal", "Insurer portal"),
                            ("visual", "Visual only"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("has_expiration", models.BooleanField(default=True)),
                ("extraction_schema", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
