# Generated by Django 5.1.15 on 2026-09-29 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("events", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when an agent uploaded this certificate for a specific event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_documents",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supersedes",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coidetails",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coi",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="documents.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="vendors.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("superseded_by__isnull", True)),
                fields=["vendor", "document_type"],
                name="doc_current_idx",
            ),
        ),
    ]
