# Generated by Django 5.1.15 on 2026-09-29 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=200)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("food_truck", "Food truck"),
                            ("caterer", "Caterer"),
                            ("rentals", "Rentals"),
                            ("other", "Other"),
                        ],
                        default="food_truck",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("service_area", models.CharField(blank=True, max_length=200)),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        help_text="Storage path of the optional photo.",
                        max_length=500,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Agent or insurer contact",
                    ),
                ),
                ("agent_email", models.EmailField(blank=True, max_length=254)),
                ("agent_phone", models.CharField(blank=True, max_length=20)),
                ("insurer_name", models.CharField(blank=True, max_length=200)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["business_name"],
            },
        ),
    ]
